export default {
  level_1: {
    background: "basic-bg",
    rotation_speed: 1,
    acceleration: 0.01,
    targets_amount: 8,
    ball_distance: 90,
    additional_angle: 22.5,
    starting_target: 1,
  },
  level_2: {
    background: "autumn-bg",
    rotation_speed: 1,
    acceleration: 0.02,
    targets_amount: 8,
    ball_distance: 110,
    additional_angle: 22.5,
    starting_target: 1,
    targets_speed: 0.3,
  },
  level_3: {
    background: "night-bg",
    rotation_speed: 1,
    acceleration: 0.03,
    targets_amount: 8,
    ball_distance: 130,
    additional_angle: 22.5,
    starting_target: 1,
  },

  level_4: {
    background: "snow-bg",
    rotation_speed: 1,
    acceleration: 0.04,
    targets_amount: 8,
    ball_distance: 100,
    additional_angle: 22.5,
    starting_target: 1,
  },
  level_5: {
    background: "reverse-bg",
    rotation_speed: 1,
    acceleration: 0.05,
    targets_amount: 8,
    ball_distance: 130,
    additional_angle: 22.5,
    starting_target: 6,
  },
  level_6: {
    background: "sunny-bg",
    rotation_speed: 0.2,
    acceleration: 0.06,
    targets_amount: 8,
    ball_distance: 130,
    additional_angle: 22.5,
    starting_target: 1,
    target_rotate_speed: 0.5,
  },
  level_7: {
    background: "purple-bg",
    rotation_speed: 1,
    acceleration: 0.07,
    targets_amount: 8,
    ball_distance: 90,
    additional_angle: 22.5,
    starting_target: 1,
  },

  level_8: {
    background: "earthquake-bg",
    rotation_speed: 1,
    acceleration: 0.06,
    targets_amount: 8,
    ball_distance: 90,
    additional_angle: 22.5,
    starting_target: 1,
  },
  level_9: {
    background: "twins-bg",
    rotation_speed: 1,
    acceleration: 0.06,
    targets_amount: 8,
    ball_distance: 90,
    additional_angle: 22.5,
    starting_target: 1,
  },
  level_10: {
    background: "speed-bg",
    rotation_speed: 1,
    acceleration: 0.06,
    targets_amount: 8,
    ball_distance: 90,
    additional_angle: 22.5,
    starting_target: 1,
    time_left: 10, //in seconds
  },
  level_11: {
    background: "perfect-bg",
    rotation_speed: 1,
    acceleration: 0.06,
    targets_amount: 8,
    ball_distance: 90,
    additional_angle: 22.5,
    starting_target: 1,
  },
}
