export default {
  level_1: {
    background: "basic-bg",
    rotation_speed: 1,
    targets_amount: 8,
    ball_distance: 90,
    additional_angle: 22.5,
    starting_target: 1,
  },
  level_2: {
    background: "autumn-bg",
    rotation_speed: 1,
    targets_amount: 8,
    ball_distance: 110,
    additional_angle: 22.5,
    starting_target: 1,
    targets_speed: 0.3,
  },
  level_3: {
    background: "night-bg",
    rotation_speed: 1,
    targets_amount: 8,
    ball_distance: 130,
    additional_angle: 22.5,
    starting_target: 1,
  },

  level_4: {
    background: "snow-bg",
    rotation_speed: 1,
    targets_amount: 8,
    ball_distance: 100,
    additional_angle: 22.5,
    starting_target: 1,
  },
  level_5: {
    background: "reverse-bg",
    rotation_speed: 1,
    targets_amount: 8,
    ball_distance: 130,
    additional_angle: 22.5,
    starting_target: 6,
  },
  level_6: {
    background: "sunny-bg",
    rotation_speed: 1,
    targets_amount: 8,
    ball_distance: 130,
    additional_angle: 22.5,
    starting_target: 1,
    target_rotate_speed: 0.5,
  },
  level_7: {
    background: "purple-bg",
    rotation_speed: 1,
    targets_amount: 8,
    ball_distance: 130,
    additional_angle: 22.5,
    starting_target: 1,
  },
};
